source 'https://rubygems.org'
group :test do
  gem 'io-console'
  gem 'poltergeist', "~> 1.9"
  gem 'selenium-webdriver'
  gem 'launchy'
  gem 'rest-client'
  gem 'json'
  gem 'cucumber'
  gem "rspec-expectations", "~> 3.4"
  gem 'capybara'
  gem 'site_prism', '~> 2.9'
  gem 'pry'
  gem 'test-unit'
  gem 'invoker'
  gem 'headless'
  gem 'rspec-core', '~> 3.4', '>= 3.4.4'
  gem 'rspec', '~> 3.4'
  gem 'rake'
  gem 'report_builder', '~> 0.1.2'
  gem 'mini_portile2'
  gem 'ruby-gmail', '~> 0.3.1'
  gem 'database_cleaner'
  gem 'rainbow', '>= 2.1.0', '< 2.2.0'
  gem 'byebug'
  gem 'nokogiri'
  gem 'activesupport'
  gem 'mysql2'
  gem 'jsonpath'
  gem 'flatpickr'
  gem 'faker'
  gem 'reportportal', git: 'https://github.com/reportportal/agent-ruby.git'
  gem 'yarpc', git: 'https://bitbucket.org/ATrush/yarpc.git'
  gem 'jenkins_api_client'
  gem 'levenshtein', '~> 0.2.2'
  gem 'parallel_tests', group: [:development, :test]
  gem 'regexp-examples'
end
